name: Publish Package to NPM
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun ci --ignore-scripts

      - name: Build
        run: bun run build:all

      - name: Audit
        run: bun audit signatures

      - name: Run Tests
        run: bun test

      - name: Get Version From Tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Publishing Version ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "Version to publish: ${{ steps.get_version.outputs.VERSION }}"

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_CONFIG_TOKEN}" > ~/.npmrc
          npm version --no-git-tag-version ${{ steps.get_version.outputs.VERSION }}
          bun publish --access public --ignore-scripts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
